apiVersion: v1
kind: Pod
metadata:
  name: iozone-pod-glusterfs
spec:
  containers:
  - name: iozone
    image: pstauffer/iozone
    imagePullPolicy: IfNotPresent
    command: ["yes"]
    volumeMounts:
    - mountPath: /glusterfs
      name: gluster-volume
      readOnly: false
  volumes:
  - name: gluster-volume
    persistentVolumeClaim:
      claimName: pvcfs
