kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcfs
  annotations:
    volume.beta.kubernetes.io/storage-class: glusterfs-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
